### ISSUE TITLE
EPG

### ISSUE THREAD

**Issue by ian10951** [oottppxx/enigma2#1]
The Catchup EPG is not passed through to the Infobar when playing a Catchup stream.

**Comment by oottppxx** [comment]
That's correct that no EPG is displayed on the info bar, and I'm not sure it ever will, due to the way enigma2 EPG system works and Heinz using as much of the default system as it can.

As a workaround, you can invoke the timebar on a catchup stream and press info, as per one of the example screenshots, it should give you the EPG description of the show, the duration, and the date it aired.

**Comment by ian10951** [comment]
Oh OK, that's a shame. I did think it was just a missing def 

Thanks for the info about the work around.

**Comment by oottppxx** [comment]
Indeed, I'd rather have it there, too.

No problem, make sure to go through the readme and look at the example screenshots.
